//! The runtime catalog: all 63 runtimes from the 2026-09-24 inference runtime
//! catalog, each with the integration decision from the runtime integration
//! plan (docs/decisions/2026-09-24-integrate-inference-runtimes-behind-one-
//! adapter-layer.md).
//!
//! The list is data, not behaviour: nothing here starts, downloads or connects
//! to anything. `verified: true` marks entries whose status facts (Windows
//! support, maintenance, licence, metrics endpoint) were re-checked against
//! the project's own repository or documentation on `verified_on`; the rest
//! carry the catalog's description and must be confirmed before an adapter
//! for them is built.

use super::descriptor::{
    ApiSurface as A, Capability as C, Format as F, Granularity, Group, Layer, License,
    LicenseClass, Maintenance, Mode, MultiGpu, Platforms, RuntimeDescriptor, Support,
    TelemetrySource as T, Tier,
};

const CHECKED: &str = "2026-09-24";

// --- platforms ---------------------------------------------------------------

const ALL: Platforms = Platforms {
    windows: Support::Native,
    linux: Support::Native,
    macos: Support::Native,
};
const WIN_LINUX: Platforms = Platforms {
    windows: Support::Native,
    linux: Support::Native,
    macos: Support::None,
};
/// Linux-first: on Windows only through WSL2 or a Linux container.
const LINUX_WSL: Platforms = Platforms {
    windows: Support::Wsl,
    linux: Support::Native,
    macos: Support::None,
};
/// Linux-first with a macOS path, no native Windows.
const LINUX_MAC_WSL: Platforms = Platforms {
    windows: Support::Wsl,
    linux: Support::Native,
    macos: Support::Native,
};
const APPLE: Platforms = Platforms {
    windows: Support::None,
    linux: Support::None,
    macos: Support::Native,
};
/// Mobile/edge targets; the desktop platforms are build hosts, not targets.
const EDGE: Platforms = Platforms {
    windows: Support::None,
    linux: Support::None,
    macos: Support::None,
};

// --- licences ----------------------------------------------------------------

const MIT: License = License {
    spdx: "MIT",
    class: LicenseClass::Permissive,
};
const APACHE: License = License {
    spdx: "Apache-2.0",
    class: LicenseClass::Permissive,
};
const BSD3: License = License {
    spdx: "BSD-3-Clause",
    class: LicenseClass::Permissive,
};
const GPL3: License = License {
    spdx: "GPL-3.0",
    class: LicenseClass::Copyleft,
};
const AGPL3: License = License {
    spdx: "AGPL-3.0",
    class: LicenseClass::Copyleft,
};
const CLOSED: License = License {
    spdx: "proprietary",
    class: LicenseClass::Proprietary,
};

// --- telemetry ---------------------------------------------------------------

const USAGE: T = T::ResponseUsage;
const TIMINGS: T = T::ResponseTimings;
const WORKER: T = T::WorkerMeasured;

// --- capability sets -----------------------------------------------------------

const TEXT: &[C] = &[C::Chat, C::Completion];
const TEXT_EMBED: &[C] = &[C::Chat, C::Completion, C::Embeddings];
const TEXT_VLM: &[C] = &[C::Chat, C::Completion, C::Vision];
const TEXT_VLM_EMBED: &[C] = &[C::Chat, C::Completion, C::Embeddings, C::Vision];
const IMAGE: &[C] = &[C::ImageGen];
const IMAGE_VIDEO: &[C] = &[C::ImageGen, C::VideoGen];
const ASR: &[C] = &[C::SpeechToText];
const EVERYTHING: &[C] = &[
    C::Chat,
    C::Completion,
    C::Embeddings,
    C::Rerank,
    C::Vision,
    C::ImageGen,
    C::VideoGen,
    C::SpeechToText,
    C::TextToSpeech,
];

const OPENAI: &[A] = &[A::OpenAiCompatible];
const OPENAI_NATIVE: &[A] = &[A::OpenAiCompatible, A::NativeHttp];
const PY: &[A] = &[A::PythonLibrary];
const NONE_WRAPS: &[&str] = &[];

/// Every runtime in the catalog, in catalog order.
pub static RUNTIMES: &[RuntimeDescriptor] = &[
    // ===== Local desktop & small servers =======================================
    RuntimeDescriptor {
        id: "llama-cpp",
        name: "llama.cpp",
        group: Group::LocalDesktop,
        tier: Tier::P0,
        mode: Mode::Bundled,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT_VLM_EMBED,
        formats: &[F::Gguf],
        apis: &[A::OpenAiCompatible, A::NativeHttp, A::Cli],
        default_port: Some(8080),
        platforms: ALL,
        multi_gpu: MultiGpu::LayerOrTensor,
        telemetry: &[
            T::Prometheus {
                path: "/metrics",
                prefix: "llamacpp:",
                needs_flag: Some("--metrics"),
            },
            T::StatusEndpoint { path: "/slots" },
            TIMINGS,
            USAGE,
        ],
        granularity: Granularity::Both,
        license: MIT,
        maintenance: Maintenance::Active,
        note: "Already Radium's chat engine (llamacpp-upstream and the TurboQuant fork). Split mode `layer` is the default; `tensor` is experimental and needs NCCL; `row` is deprecated.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://github.com/ggml-org/llama.cpp",
    },
    RuntimeDescriptor {
        id: "ollama",
        name: "Ollama",
        group: Group::LocalDesktop,
        tier: Tier::P0,
        mode: Mode::Attach,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT_VLM_EMBED,
        formats: &[F::OllamaPackage, F::Gguf, F::Safetensors],
        apis: OPENAI_NATIVE,
        default_port: Some(11434),
        platforms: ALL,
        multi_gpu: MultiGpu::LayerSplit,
        telemetry: &[TIMINGS, T::StatusEndpoint { path: "/api/ps" }, USAGE],
        granularity: Granularity::PerRequest,
        license: MIT,
        maintenance: Maintenance::Active,
        note: "A model that fits one GPU loads on one GPU. Pin cards with CUDA_VISIBLE_DEVICES by UUID; OLLAMA_SCHED_SPREAD spreads across both. No native Prometheus endpoint.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://docs.ollama.com/",
    },
    RuntimeDescriptor {
        id: "lm-studio",
        name: "LM Studio",
        group: Group::LocalDesktop,
        tier: Tier::P0,
        mode: Mode::Attach,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT_VLM_EMBED,
        formats: &[F::Gguf, F::Mlx],
        apis: &[A::OpenAiCompatible, A::NativeHttp, A::Cli],
        default_port: Some(1234),
        platforms: ALL,
        multi_gpu: MultiGpu::LayerSplit,
        telemetry: &[TIMINGS, USAGE],
        granularity: Granularity::PerRequest,
        license: CLOSED,
        maintenance: Maintenance::Active,
        note: "Closed source: attach only. `/v1/models` lists loaded models only; the native REST API reports tokens/s and time to first token. MLX is Apple only.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://lmstudio.ai/docs/developer",
    },
    RuntimeDescriptor {
        id: "radium",
        name: "Radium",
        group: Group::LocalDesktop,
        tier: Tier::P0,
        mode: Mode::InProcess,
        layer: Layer::Wrapper,
        wraps: &["llama-cpp", "stable-diffusion-cpp"],
        capabilities: TEXT_VLM_EMBED,
        formats: &[F::Gguf],
        apis: OPENAI,
        default_port: Some(1337),
        platforms: ALL,
        multi_gpu: MultiGpu::FromBackend,
        telemetry: &[USAGE],
        granularity: Granularity::PerRequest,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "This app: the OpenAI-compatible facade at localhost:1337/v1. It is a wrapper layer, so it never counts tokens itself.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://github.com/walladanger/Radium",
    },
    RuntimeDescriptor {
        id: "jan",
        name: "Jan",
        group: Group::LocalDesktop,
        tier: Tier::P1,
        mode: Mode::Attach,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT_VLM_EMBED,
        formats: &[F::Gguf, F::Mlx],
        apis: OPENAI,
        default_port: Some(1337),
        platforms: ALL,
        multi_gpu: MultiGpu::LayerSplit,
        telemetry: &[USAGE],
        granularity: Granularity::PerRequest,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Jan's local API server also binds 127.0.0.1:1337 and does not fall back to another port, so it collides with Radium's own server.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://www.jan.ai/docs/desktop/manage-models",
    },
    RuntimeDescriptor {
        id: "gpt4all",
        name: "GPT4All",
        group: Group::LocalDesktop,
        tier: Tier::P2,
        mode: Mode::Attach,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT,
        formats: &[F::Gguf],
        apis: OPENAI,
        default_port: Some(4891),
        platforms: ALL,
        multi_gpu: MultiGpu::PerProcess,
        telemetry: &[USAGE],
        granularity: Granularity::PerRequest,
        license: MIT,
        maintenance: Maintenance::LowActivity,
        note: "Latest GitHub release v3.10.0 (Feb 2025). The local server is opt-in in its settings.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://docs.gpt4all.io/",
    },
    RuntimeDescriptor {
        id: "koboldcpp",
        name: "KoboldCpp",
        group: Group::LocalDesktop,
        tier: Tier::P0,
        mode: Mode::Attach,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: &[C::Chat, C::Completion, C::Vision, C::ImageGen, C::SpeechToText, C::TextToSpeech],
        formats: &[F::Gguf, F::GgmlBin],
        apis: &[A::OpenAiCompatible, A::NativeHttp, A::SdApi],
        default_port: Some(5001),
        platforms: ALL,
        multi_gpu: MultiGpu::LayerSplit,
        telemetry: &[T::StatusEndpoint { path: "/api/extra/perf" }, USAGE],
        granularity: Granularity::Both,
        license: AGPL3,
        maintenance: Maintenance::Active,
        note: "AGPL-3.0: attach now; a managed download of the single exe comes later, never bundled.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://github.com/LostRuins/koboldcpp",
    },
    RuntimeDescriptor {
        id: "localai",
        name: "LocalAI",
        group: Group::LocalDesktop,
        tier: Tier::P3,
        mode: Mode::Attach,
        layer: Layer::Wrapper,
        wraps: &["llama-cpp", "vllm", "hf-transformers", "hf-diffusers", "whisper-cpp", "piper", "stable-diffusion-cpp"],
        capabilities: EVERYTHING,
        formats: &[F::Gguf, F::Safetensors, F::Mlx, F::Onnx],
        apis: OPENAI,
        default_port: Some(8080),
        platforms: LINUX_MAC_WSL,
        multi_gpu: MultiGpu::FromBackend,
        telemetry: &[USAGE],
        granularity: Granularity::PerRequest,
        license: MIT,
        maintenance: Maintenance::Active,
        note: "Multi-backend wrapper: attribute tokens to the backend it selected, not to LocalAI.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://github.com/mudler/LocalAI",
    },
    RuntimeDescriptor {
        id: "mistral-rs",
        name: "mistral.rs",
        group: Group::LocalDesktop,
        tier: Tier::P2,
        mode: Mode::Bundled,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT_VLM,
        formats: &[F::Safetensors, F::Gguf],
        apis: &[A::OpenAiCompatible, A::PythonLibrary],
        default_port: None,
        platforms: ALL,
        multi_gpu: MultiGpu::LayerSplit,
        telemetry: &[USAGE],
        granularity: Granularity::PerRequest,
        license: MIT,
        maintenance: Maintenance::Active,
        note: "Check prebuilt Windows CUDA availability and the model matrix before building an adapter.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://docs.mistralrs.dev/",
    },
    RuntimeDescriptor {
        id: "mlc-llm",
        name: "MLC LLM",
        group: Group::LocalDesktop,
        tier: Tier::P3,
        mode: Mode::ManagedInstall,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT_VLM,
        formats: &[F::Mlc],
        apis: &[A::OpenAiCompatible, A::PythonLibrary],
        default_port: Some(8000),
        platforms: ALL,
        multi_gpu: MultiGpu::TensorParallel,
        telemetry: &[USAGE],
        granularity: Granularity::PerRequest,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Needs a per-model compile step; does not read raw GGUF.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://llm.mlc.ai/",
    },
    RuntimeDescriptor {
        id: "mlx-lm",
        name: "MLX LM",
        group: Group::LocalDesktop,
        tier: Tier::OutOfScope,
        mode: Mode::OutOfScope,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT,
        formats: &[F::Mlx, F::Safetensors],
        apis: &[A::OpenAiCompatible, A::PythonLibrary],
        default_port: None,
        platforms: APPLE,
        multi_gpu: MultiGpu::NotApplicable,
        telemetry: &[],
        granularity: Granularity::None,
        license: MIT,
        maintenance: Maintenance::Active,
        note: "Apple Silicon only. Radium's macOS builds already ship MLX through mlx-extension.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://github.com/ml-explore/mlx-lm",
    },
    RuntimeDescriptor {
        id: "exllamav2",
        name: "ExLlamaV2",
        group: Group::LocalDesktop,
        tier: Tier::Deferred,
        mode: Mode::ManagedInstall,
        layer: Layer::Library,
        wraps: NONE_WRAPS,
        capabilities: TEXT,
        formats: &[F::Exl2, F::Gptq],
        apis: PY,
        default_port: None,
        platforms: WIN_LINUX,
        multi_gpu: MultiGpu::LayerSplit,
        telemetry: &[],
        granularity: Granularity::None,
        license: MIT,
        maintenance: Maintenance::Archived,
        note: "Archived; development continues in ExLlamaV3. Reachable only through TabbyAPI's exl2-checkpoint branch.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://github.com/turboderp-org/exllamav2",
    },
    RuntimeDescriptor {
        id: "exllamav3",
        name: "ExLlamaV3",
        group: Group::LocalDesktop,
        tier: Tier::P1,
        mode: Mode::ManagedInstall,
        layer: Layer::Library,
        wraps: NONE_WRAPS,
        capabilities: TEXT_VLM,
        formats: &[F::Exl3],
        apis: PY,
        default_port: None,
        platforms: WIN_LINUX,
        multi_gpu: MultiGpu::TensorParallel,
        telemetry: &[],
        granularity: Granularity::None,
        license: MIT,
        maintenance: Maintenance::Active,
        note: "Tensor- and expert-parallel on consumer GPUs: the best native-Windows way to use both 3090s on one model. Served through TabbyAPI.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://github.com/turboderp-org/exllamav3",
    },
    RuntimeDescriptor {
        id: "tabbyapi",
        name: "TabbyAPI",
        group: Group::LocalDesktop,
        tier: Tier::P1,
        mode: Mode::ManagedInstall,
        layer: Layer::Wrapper,
        wraps: &["exllamav3", "exllamav2"],
        capabilities: TEXT_EMBED,
        formats: &[F::Exl3, F::Exl2, F::Gptq],
        apis: OPENAI,
        default_port: Some(5000),
        platforms: WIN_LINUX,
        multi_gpu: MultiGpu::FromBackend,
        telemetry: &[USAGE],
        granularity: Granularity::PerRequest,
        license: AGPL3,
        maintenance: Maintenance::Active,
        note: "Wrapper: attribute tokens to ExLlamaV3. Self-described hobby project; pin a commit.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://github.com/theroyallab/tabbyAPI",
    },
    RuntimeDescriptor {
        id: "llama-cpp-python",
        name: "llama-cpp-python",
        group: Group::LocalDesktop,
        tier: Tier::P1,
        mode: Mode::ManagedInstall,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT_VLM_EMBED,
        formats: &[F::Gguf],
        apis: &[A::OpenAiCompatible, A::PythonLibrary],
        default_port: Some(8000),
        platforms: ALL,
        multi_gpu: MultiGpu::LayerSplit,
        telemetry: &[USAGE],
        granularity: Granularity::PerRequest,
        license: MIT,
        maintenance: Maintenance::LowActivity,
        note: "CUDA on Windows usually needs a source build. Same engine as llama.cpp, so report backend llama-cpp.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://github.com/abetlen/llama-cpp-python",
    },
    // ===== Throughput servers & orchestration =================================
    RuntimeDescriptor {
        id: "vllm",
        name: "vLLM",
        group: Group::ThroughputServer,
        tier: Tier::P2,
        mode: Mode::WslHosted,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT_VLM_EMBED,
        formats: &[F::Safetensors, F::Gptq, F::Awq, F::Fp8, F::Gguf],
        apis: OPENAI,
        default_port: Some(8000),
        platforms: LINUX_WSL,
        multi_gpu: MultiGpu::TensorParallel,
        telemetry: &[
            T::Prometheus {
                path: "/metrics",
                prefix: "vllm:",
                needs_flag: None,
            },
            USAGE,
        ],
        granularity: Granularity::Both,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "No native Windows support; WSL2 is the official path. TP=2 on PCIe-only 3090s is interconnect-bound.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://docs.vllm.ai/",
    },
    RuntimeDescriptor {
        id: "sglang",
        name: "SGLang",
        group: Group::ThroughputServer,
        tier: Tier::P2,
        mode: Mode::WslHosted,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: &[C::Chat, C::Completion, C::Embeddings, C::Vision, C::ImageGen, C::VideoGen],
        formats: &[F::Safetensors, F::Gptq, F::Awq, F::Fp8],
        apis: OPENAI_NATIVE,
        default_port: Some(30000),
        platforms: LINUX_WSL,
        multi_gpu: MultiGpu::TensorParallel,
        telemetry: &[
            T::Prometheus {
                path: "/metrics",
                prefix: "sglang:",
                needs_flag: Some("--enable-metrics"),
            },
            USAGE,
        ],
        granularity: Granularity::Both,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Under tensor parallelism only rank 0 records request metrics by default; per-rank metrics double every sum unless filtered by tp_rank.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://github.com/sgl-project/sglang",
    },
    RuntimeDescriptor {
        id: "hf-tgi",
        name: "HF Text Generation Inference",
        group: Group::ThroughputServer,
        tier: Tier::Deferred,
        mode: Mode::Attach,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT_VLM,
        formats: &[F::Safetensors, F::Gptq, F::Awq, F::Exl2, F::Fp8],
        apis: OPENAI_NATIVE,
        default_port: None,
        platforms: LINUX_WSL,
        multi_gpu: MultiGpu::TensorParallel,
        telemetry: &[
            T::Prometheus {
                path: "/metrics",
                prefix: "tgi_",
                needs_flag: None,
            },
            USAGE,
        ],
        granularity: Granularity::Both,
        license: APACHE,
        maintenance: Maintenance::MaintenanceMode,
        note: "In maintenance mode since 2025-12-11; Hugging Face recommends vLLM or SGLang. Attach only.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://huggingface.co/docs/text-generation-inference/index",
    },
    RuntimeDescriptor {
        id: "tensorrt-llm",
        name: "TensorRT-LLM",
        group: Group::ThroughputServer,
        tier: Tier::Deferred,
        mode: Mode::WslHosted,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT_VLM,
        formats: &[F::Safetensors, F::TensorrtEngine],
        apis: &[A::OpenAiCompatible, A::PythonLibrary],
        default_port: Some(8000),
        platforms: LINUX_WSL,
        multi_gpu: MultiGpu::TensorParallel,
        telemetry: &[USAGE],
        granularity: Granularity::PerRequest,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "All Windows code is slated for removal. Collects anonymous telemetry by default: disable it if ever run.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://github.com/NVIDIA/TensorRT-LLM",
    },
    RuntimeDescriptor {
        id: "nvidia-triton",
        name: "NVIDIA Triton",
        group: Group::ThroughputServer,
        tier: Tier::P3,
        mode: Mode::WslHosted,
        layer: Layer::Wrapper,
        wraps: &["tensorrt", "onnx-runtime", "pytorch", "openvino-model-server", "vllm", "tensorrt-llm"],
        capabilities: EVERYTHING,
        formats: &[F::TensorrtEngine, F::Onnx, F::PytorchBin, F::OpenvinoIr],
        apis: &[A::KserveV2, A::OpenAiCompatible],
        default_port: Some(8000),
        platforms: LINUX_WSL,
        multi_gpu: MultiGpu::FromBackend,
        telemetry: &[T::Prometheus {
            path: "/metrics",
            prefix: "nv_",
            needs_flag: None,
        }],
        granularity: Granularity::Aggregate,
        license: BSD3,
        maintenance: Maintenance::Active,
        note: "Host layer with pluggable backends. Metrics are on port 8002, not the HTTP port.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://docs.nvidia.com/deeplearning/triton-inference-server/",
    },
    RuntimeDescriptor {
        id: "nvidia-nim",
        name: "NVIDIA NIM",
        group: Group::ThroughputServer,
        tier: Tier::Deferred,
        mode: Mode::WslHosted,
        layer: Layer::Wrapper,
        wraps: &["tensorrt-llm", "vllm", "sglang"],
        capabilities: TEXT_VLM_EMBED,
        formats: &[F::Safetensors, F::Gguf, F::TensorrtEngine],
        apis: OPENAI,
        default_port: Some(8000),
        platforms: LINUX_WSL,
        multi_gpu: MultiGpu::FromBackend,
        telemetry: &[USAGE],
        granularity: Granularity::PerRequest,
        license: CLOSED,
        maintenance: Maintenance::Active,
        note: "Container images need an NGC account and licence; RTX 3090 support is per profile.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://docs.nvidia.com/nim/",
    },
    RuntimeDescriptor {
        id: "nvidia-dynamo",
        name: "NVIDIA Dynamo",
        group: Group::ThroughputServer,
        tier: Tier::OutOfScope,
        mode: Mode::OutOfScope,
        layer: Layer::Wrapper,
        wraps: &["vllm", "sglang", "tensorrt-llm"],
        capabilities: TEXT_VLM,
        formats: &[],
        apis: OPENAI,
        default_port: None,
        platforms: LINUX_WSL,
        multi_gpu: MultiGpu::FromBackend,
        telemetry: &[],
        granularity: Granularity::None,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Datacentre disaggregated serving: no value on one workstation. Its dynamo_* metrics share an endpoint with the backend's, a double-count trap.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://docs.nvidia.com/dynamo/",
    },
    RuntimeDescriptor {
        id: "lmdeploy",
        name: "LMDeploy",
        group: Group::ThroughputServer,
        tier: Tier::P3,
        mode: Mode::WslHosted,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT_VLM,
        formats: &[F::Safetensors, F::Awq],
        apis: OPENAI,
        default_port: Some(23333),
        platforms: LINUX_WSL,
        multi_gpu: MultiGpu::TensorParallel,
        telemetry: &[USAGE],
        granularity: Granularity::PerRequest,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Check native Windows wheels before choosing WSL.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://lmdeploy.readthedocs.io/",
    },
    RuntimeDescriptor {
        id: "xinference",
        name: "Xinference",
        group: Group::ThroughputServer,
        tier: Tier::P3,
        mode: Mode::Attach,
        layer: Layer::Wrapper,
        wraps: &["llama-cpp", "vllm", "hf-transformers", "sglang", "sentence-transformers"],
        capabilities: EVERYTHING,
        formats: &[F::Gguf, F::Safetensors],
        apis: OPENAI_NATIVE,
        default_port: Some(9997),
        platforms: LINUX_MAC_WSL,
        multi_gpu: MultiGpu::FromBackend,
        telemetry: &[USAGE],
        granularity: Granularity::PerRequest,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Wrapper with its own model registry: attribute to the engine it launched.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://inference.readthedocs.io/",
    },
    RuntimeDescriptor {
        id: "ray-serve-llm",
        name: "Ray Serve LLM",
        group: Group::ThroughputServer,
        tier: Tier::Deferred,
        mode: Mode::WslHosted,
        layer: Layer::Wrapper,
        wraps: &["vllm", "sglang"],
        capabilities: TEXT_VLM_EMBED,
        formats: &[F::Safetensors],
        apis: OPENAI,
        default_port: Some(8000),
        platforms: LINUX_WSL,
        multi_gpu: MultiGpu::FromBackend,
        telemetry: &[USAGE],
        granularity: Granularity::PerRequest,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Distributed orchestration; its vLLM backend needs Linux anyway.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://docs.ray.io/en/latest/serve/llm/index.html",
    },
    RuntimeDescriptor {
        id: "bentoml",
        name: "BentoML",
        group: Group::ThroughputServer,
        tier: Tier::Deferred,
        mode: Mode::Attach,
        layer: Layer::Wrapper,
        wraps: &["vllm", "hf-transformers", "onnx-runtime", "pytorch"],
        capabilities: EVERYTHING,
        formats: &[],
        apis: &[A::NativeHttp, A::OpenAiCompatible],
        default_port: Some(3000),
        platforms: ALL,
        multi_gpu: MultiGpu::FromBackend,
        telemetry: &[],
        granularity: Granularity::None,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Packages services; not a checkpoint loader. Monitor the concrete engine inside the service.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://docs.bentoml.org/",
    },
    RuntimeDescriptor {
        id: "deepspeed-mii",
        name: "DeepSpeed-MII",
        group: Group::ThroughputServer,
        tier: Tier::Deferred,
        mode: Mode::WslHosted,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT,
        formats: &[F::Safetensors, F::PytorchBin],
        apis: &[A::PythonLibrary, A::NativeHttp],
        default_port: None,
        platforms: LINUX_WSL,
        multi_gpu: MultiGpu::TensorParallel,
        telemetry: &[],
        granularity: Granularity::None,
        license: APACHE,
        maintenance: Maintenance::LowActivity,
        note: "Linux-first; vLLM and SGLang cover the same ground better on this hardware.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://github.com/deepspeedai/DeepSpeed-MII",
    },
    RuntimeDescriptor {
        id: "lightllm",
        name: "LightLLM",
        group: Group::ThroughputServer,
        tier: Tier::Deferred,
        mode: Mode::WslHosted,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT,
        formats: &[F::Safetensors],
        apis: &[A::NativeHttp, A::OpenAiCompatible],
        default_port: None,
        platforms: LINUX_WSL,
        multi_gpu: MultiGpu::TensorParallel,
        telemetry: &[],
        granularity: Granularity::None,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Linux-only server; check the model matrix before import.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://github.com/ModelTC/lightllm",
    },
    RuntimeDescriptor {
        id: "aphrodite",
        name: "Aphrodite Engine",
        group: Group::ThroughputServer,
        tier: Tier::P2,
        mode: Mode::WslHosted,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT_VLM,
        formats: &[F::Safetensors, F::Gguf, F::Exl3, F::Gptq, F::Awq],
        apis: OPENAI_NATIVE,
        default_port: Some(2242),
        platforms: LINUX_WSL,
        multi_gpu: MultiGpu::TensorParallel,
        telemetry: &[
            T::Prometheus {
                path: "/metrics",
                prefix: "aphrodite:",
                needs_flag: None,
            },
            USAGE,
        ],
        granularity: Granularity::Both,
        license: AGPL3,
        maintenance: Maintenance::Active,
        note: "vLLM fork with a Kobold-compatible API. Confirm the metric prefix against the pinned version.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://github.com/aphrodite-engine/aphrodite-engine",
    },
    RuntimeDescriptor {
        id: "openvino-model-server",
        name: "OpenVINO Model Server",
        group: Group::ThroughputServer,
        tier: Tier::P3,
        mode: Mode::Attach,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT_VLM_EMBED,
        formats: &[F::OpenvinoIr, F::Onnx, F::Gguf],
        apis: &[A::OpenAiCompatible, A::KserveV2],
        default_port: None,
        platforms: WIN_LINUX,
        multi_gpu: MultiGpu::NotApplicable,
        telemetry: &[T::Prometheus {
            path: "/metrics",
            prefix: "ovms_",
            needs_flag: Some("--metrics_enable"),
        }],
        granularity: Granularity::Aggregate,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Intel-optimised: CPU-only on an NVIDIA workstation, so low value here.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://docs.openvino.ai/2026/model-server/ovms_what_is_openvino_model_server.html",
    },
    // ===== General model libraries ============================================
    RuntimeDescriptor {
        id: "pytorch",
        name: "PyTorch",
        group: Group::ModelLibrary,
        tier: Tier::P1,
        mode: Mode::ManagedInstall,
        layer: Layer::Library,
        wraps: NONE_WRAPS,
        capabilities: EVERYTHING,
        formats: &[F::PytorchBin, F::Safetensors],
        apis: PY,
        default_port: None,
        platforms: ALL,
        multi_gpu: MultiGpu::NotApplicable,
        telemetry: &[WORKER],
        granularity: Granularity::None,
        license: BSD3,
        maintenance: Maintenance::Active,
        note: "Dependency of Radium's Python worker, not an endpoint.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://pytorch.org/docs/stable/index.html",
    },
    RuntimeDescriptor {
        id: "hf-transformers",
        name: "HF Transformers",
        group: Group::ModelLibrary,
        tier: Tier::P1,
        mode: Mode::ManagedInstall,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: &[C::Chat, C::Completion, C::Embeddings, C::Rerank, C::Vision, C::SpeechToText],
        formats: &[F::Safetensors, F::PytorchBin, F::Gptq, F::Awq],
        apis: PY,
        default_port: None,
        platforms: ALL,
        multi_gpu: MultiGpu::LayerSplit,
        telemetry: &[WORKER],
        granularity: Granularity::PerRequest,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Served by Radium's Python worker. device_map=auto spans both GPUs sequentially.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://huggingface.co/docs/transformers/main/models",
    },
    RuntimeDescriptor {
        id: "hf-diffusers",
        name: "HF Diffusers",
        group: Group::ModelLibrary,
        tier: Tier::P1,
        mode: Mode::ManagedInstall,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: IMAGE_VIDEO,
        formats: &[F::DiffusersFolder, F::Safetensors, F::Ckpt],
        apis: PY,
        default_port: None,
        platforms: ALL,
        multi_gpu: MultiGpu::PerProcess,
        telemetry: &[WORKER],
        granularity: Granularity::PerRequest,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "One pipeline per GPU; shares the media job API with stable-diffusion.cpp.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://huggingface.co/docs/diffusers/index",
    },
    RuntimeDescriptor {
        id: "hf-accelerate",
        name: "HF Accelerate",
        group: Group::ModelLibrary,
        tier: Tier::P1,
        mode: Mode::ManagedInstall,
        layer: Layer::Library,
        wraps: NONE_WRAPS,
        capabilities: &[],
        formats: &[F::Safetensors, F::PytorchBin],
        apis: PY,
        default_port: None,
        platforms: ALL,
        multi_gpu: MultiGpu::LayerSplit,
        telemetry: &[],
        granularity: Granularity::None,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Device placement and offload for Transformers/Diffusers; not a server.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://huggingface.co/docs/accelerate/main/usage_guides/big_modeling",
    },
    RuntimeDescriptor {
        id: "onnx-runtime",
        name: "ONNX Runtime",
        group: Group::ModelLibrary,
        tier: Tier::P0,
        mode: Mode::ManagedInstall,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: &[C::Embeddings, C::Rerank, C::Vision, C::SpeechToText, C::TextToSpeech, C::ImageGen],
        formats: &[F::Onnx],
        apis: &[A::CLibrary, A::PythonLibrary],
        default_port: None,
        platforms: ALL,
        multi_gpu: MultiGpu::PerProcess,
        telemetry: &[WORKER],
        granularity: Granularity::PerRequest,
        license: MIT,
        maintenance: Maintenance::Active,
        note: "Use the CUDA execution provider on the 3090s. DirectML is in sustained engineering; new work moved to WinML.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://onnxruntime.ai/docs/",
    },
    RuntimeDescriptor {
        id: "onnx-runtime-genai",
        name: "ONNX Runtime GenAI",
        group: Group::ModelLibrary,
        tier: Tier::P1,
        mode: Mode::ManagedInstall,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT_VLM,
        formats: &[F::Onnx],
        apis: &[A::CLibrary, A::PythonLibrary],
        default_port: None,
        platforms: ALL,
        multi_gpu: MultiGpu::PerProcess,
        telemetry: &[WORKER],
        granularity: Granularity::PerRequest,
        license: MIT,
        maintenance: Maintenance::Active,
        note: "Generation loop and KV cache over ONNX Runtime; needs an exported model plus genai_config.json.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://onnxruntime.ai/docs/genai/",
    },
    RuntimeDescriptor {
        id: "openvino-genai",
        name: "OpenVINO GenAI",
        group: Group::ModelLibrary,
        tier: Tier::P3,
        mode: Mode::ManagedInstall,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: &[C::Chat, C::Completion, C::Vision, C::SpeechToText, C::ImageGen],
        formats: &[F::OpenvinoIr],
        apis: &[A::PythonLibrary, A::CLibrary],
        default_port: None,
        platforms: ALL,
        multi_gpu: MultiGpu::NotApplicable,
        telemetry: &[WORKER],
        granularity: Granularity::PerRequest,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "A route for Intel hardware; CPU-only here.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://docs.openvino.ai/2025/openvino-workflow-generative/inference-with-genai.html",
    },
    RuntimeDescriptor {
        id: "tensorrt",
        name: "NVIDIA TensorRT",
        group: Group::ModelLibrary,
        tier: Tier::Deferred,
        mode: Mode::ManagedInstall,
        layer: Layer::Library,
        wraps: NONE_WRAPS,
        capabilities: &[C::Vision, C::ImageGen, C::SpeechToText],
        formats: &[F::Onnx, F::TensorrtEngine],
        apis: &[A::CLibrary, A::PythonLibrary],
        default_port: None,
        platforms: WIN_LINUX,
        multi_gpu: MultiGpu::PerProcess,
        telemetry: &[],
        granularity: Granularity::None,
        license: CLOSED,
        maintenance: Maintenance::Active,
        note: "Use through ONNX Runtime's TensorRT execution provider. Engines are tied to the GPU and driver they were built on.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://docs.nvidia.com/deeplearning/tensorrt/latest/",
    },
    RuntimeDescriptor {
        id: "tensorflow",
        name: "TensorFlow / Keras",
        group: Group::ModelLibrary,
        tier: Tier::OutOfScope,
        mode: Mode::OutOfScope,
        layer: Layer::Library,
        wraps: NONE_WRAPS,
        capabilities: &[],
        formats: &[F::TfSavedModel, F::Tflite],
        apis: PY,
        default_port: None,
        platforms: LINUX_MAC_WSL,
        multi_gpu: MultiGpu::NotApplicable,
        telemetry: &[],
        granularity: Granularity::None,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "TensorFlow 2.10 was the last release with GPU support on native Windows; WSL2 only since. Low value for local LLMs.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://www.tensorflow.org/install/pip",
    },
    RuntimeDescriptor {
        id: "jax",
        name: "JAX / Flax",
        group: Group::ModelLibrary,
        tier: Tier::OutOfScope,
        mode: Mode::OutOfScope,
        layer: Layer::Library,
        wraps: NONE_WRAPS,
        capabilities: &[],
        formats: &[F::Orbax],
        apis: PY,
        default_port: None,
        platforms: LINUX_MAC_WSL,
        multi_gpu: MultiGpu::NotApplicable,
        telemetry: &[],
        granularity: Granularity::None,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "No native-Windows CUDA; needs an explicit model implementation per model.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://flax.readthedocs.io/",
    },
    RuntimeDescriptor {
        id: "apple-mlx",
        name: "Apple MLX",
        group: Group::ModelLibrary,
        tier: Tier::OutOfScope,
        mode: Mode::OutOfScope,
        layer: Layer::Library,
        wraps: NONE_WRAPS,
        capabilities: &[],
        formats: &[F::Mlx, F::Safetensors],
        apis: PY,
        default_port: None,
        platforms: APPLE,
        multi_gpu: MultiGpu::NotApplicable,
        telemetry: &[],
        granularity: Granularity::None,
        license: MIT,
        maintenance: Maintenance::Active,
        note: "Apple Silicon only.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://ml-explore.github.io/mlx/",
    },
    RuntimeDescriptor {
        id: "ctranslate2",
        name: "CTranslate2",
        group: Group::ModelLibrary,
        tier: Tier::P1,
        mode: Mode::ManagedInstall,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: &[C::Completion, C::SpeechToText],
        formats: &[F::Ct2],
        apis: &[A::PythonLibrary, A::CLibrary],
        default_port: None,
        platforms: ALL,
        multi_gpu: MultiGpu::PerProcess,
        telemetry: &[WORKER],
        granularity: Granularity::PerRequest,
        license: MIT,
        maintenance: Maintenance::Active,
        note: "The engine under faster-whisper; ordinary HF weights need conversion first.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://github.com/OpenNMT/CTranslate2",
    },
    RuntimeDescriptor {
        id: "sentence-transformers",
        name: "Sentence Transformers",
        group: Group::ModelLibrary,
        tier: Tier::P1,
        mode: Mode::ManagedInstall,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: &[C::Embeddings, C::Rerank],
        formats: &[F::Safetensors, F::PytorchBin, F::Onnx, F::OpenvinoIr],
        apis: PY,
        default_port: None,
        platforms: ALL,
        multi_gpu: MultiGpu::PerProcess,
        telemetry: &[WORKER],
        granularity: Granularity::PerRequest,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Backs /v1/embeddings and /v1/rerank through Radium's Python worker.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://sbert.net/",
    },
    RuntimeDescriptor {
        id: "fastembed",
        name: "FastEmbed",
        group: Group::ModelLibrary,
        tier: Tier::P2,
        mode: Mode::ManagedInstall,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: &[C::Embeddings, C::Rerank],
        formats: &[F::Onnx],
        apis: PY,
        default_port: None,
        platforms: ALL,
        multi_gpu: MultiGpu::PerProcess,
        telemetry: &[WORKER],
        granularity: Granularity::PerRequest,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Curated ONNX embedding models over ONNX Runtime.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://qdrant.github.io/fastembed/",
    },
    RuntimeDescriptor {
        id: "transformers-js",
        name: "Transformers.js",
        group: Group::ModelLibrary,
        tier: Tier::P3,
        mode: Mode::InProcess,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: &[C::Embeddings, C::Vision, C::SpeechToText],
        formats: &[F::Onnx],
        apis: &[A::JavaScript],
        default_port: None,
        platforms: ALL,
        multi_gpu: MultiGpu::NotApplicable,
        telemetry: &[WORKER],
        granularity: Granularity::PerRequest,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Optional, in the web view (WebGPU/WASM) for small in-UI models.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://huggingface.co/docs/transformers.js/",
    },
    // ===== Image, video & speech ==============================================
    RuntimeDescriptor {
        id: "comfyui",
        name: "ComfyUI",
        group: Group::ImageVideoSpeech,
        tier: Tier::P0,
        mode: Mode::Attach,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: IMAGE_VIDEO,
        formats: &[F::Safetensors, F::Gguf, F::Ckpt],
        apis: &[A::NativeHttp],
        default_port: Some(8188),
        platforms: ALL,
        multi_gpu: MultiGpu::PerProcess,
        telemetry: &[
            T::StatusEndpoint {
                path: "/system_stats",
            },
            T::WebSocketEvents { path: "/ws" },
        ],
        granularity: Granularity::PerRequest,
        license: GPL3,
        maintenance: Maintenance::Active,
        note: "Already a Radium Media provider. No authentication: never expose beyond loopback. One GPU per process, so two instances for two cards.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://docs.comfy.org/",
    },
    RuntimeDescriptor {
        id: "invokeai",
        name: "InvokeAI",
        group: Group::ImageVideoSpeech,
        tier: Tier::P3,
        mode: Mode::Attach,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: IMAGE,
        formats: &[F::Safetensors, F::DiffusersFolder, F::Ckpt],
        apis: &[A::NativeHttp],
        default_port: Some(9090),
        platforms: ALL,
        multi_gpu: MultiGpu::PerProcess,
        telemetry: &[],
        granularity: Granularity::PerRequest,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Queue and session events carry progress; confirm the REST paths before building.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://invoke.ai/",
    },
    RuntimeDescriptor {
        id: "automatic1111",
        name: "AUTOMATIC1111 WebUI",
        group: Group::ImageVideoSpeech,
        tier: Tier::Deferred,
        mode: Mode::Attach,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: IMAGE,
        formats: &[F::Safetensors, F::Ckpt],
        apis: &[A::SdApi],
        default_port: Some(7860),
        platforms: ALL,
        multi_gpu: MultiGpu::PerProcess,
        telemetry: &[T::StatusEndpoint {
            path: "/sdapi/v1/progress",
        }],
        granularity: Granularity::PerRequest,
        license: AGPL3,
        maintenance: Maintenance::LowActivity,
        note: "No release since v1.10.1 (July 2024). The API needs --api.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
    },
    RuntimeDescriptor {
        id: "sd-webui-forge",
        name: "SD WebUI Forge",
        group: Group::ImageVideoSpeech,
        tier: Tier::P3,
        mode: Mode::Attach,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: IMAGE,
        formats: &[F::Safetensors, F::Ckpt, F::Gguf],
        apis: &[A::SdApi],
        default_port: Some(7860),
        platforms: ALL,
        multi_gpu: MultiGpu::PerProcess,
        telemetry: &[T::StatusEndpoint {
            path: "/sdapi/v1/progress",
        }],
        granularity: Granularity::PerRequest,
        license: AGPL3,
        maintenance: Maintenance::Active,
        note: "Same /sdapi/v1 API and default port as AUTOMATIC1111, so the two cannot be told apart by that API alone.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://github.com/lllyasviel/stable-diffusion-webui-forge",
    },
    RuntimeDescriptor {
        id: "swarmui",
        name: "SwarmUI",
        group: Group::ImageVideoSpeech,
        tier: Tier::P3,
        mode: Mode::Attach,
        layer: Layer::Wrapper,
        wraps: &["comfyui"],
        capabilities: IMAGE_VIDEO,
        formats: &[F::Safetensors, F::Gguf],
        apis: &[A::NativeHttp],
        default_port: Some(7801),
        platforms: ALL,
        multi_gpu: MultiGpu::FromBackend,
        telemetry: &[],
        granularity: Granularity::PerRequest,
        license: MIT,
        maintenance: Maintenance::Active,
        note: "Front end over ComfyUI backends: attribute work to ComfyUI.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://github.com/mcmonkeyprojects/SwarmUI",
    },
    RuntimeDescriptor {
        id: "stable-diffusion-cpp",
        name: "stable-diffusion.cpp",
        group: Group::ImageVideoSpeech,
        tier: Tier::P0,
        mode: Mode::Bundled,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: IMAGE_VIDEO,
        formats: &[F::Gguf, F::Safetensors],
        apis: &[A::NativeHttp],
        default_port: None,
        platforms: ALL,
        multi_gpu: MultiGpu::PerProcess,
        telemetry: &[WORKER],
        granularity: Granularity::PerRequest,
        license: MIT,
        maintenance: Maintenance::Active,
        note: "Radium's built-in media engine (release master-866-42d6c0a). CUDA build still to be validated on the dual-3090 desktop.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://github.com/leejet/stable-diffusion.cpp",
    },
    RuntimeDescriptor {
        id: "whisper-cpp",
        name: "whisper.cpp",
        group: Group::ImageVideoSpeech,
        tier: Tier::P0,
        mode: Mode::Bundled,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: ASR,
        formats: &[F::GgmlBin],
        apis: &[A::NativeHttp, A::Cli],
        default_port: Some(8080),
        platforms: ALL,
        multi_gpu: MultiGpu::PerProcess,
        telemetry: &[WORKER],
        granularity: Granularity::PerRequest,
        license: MIT,
        maintenance: Maintenance::Active,
        note: "whisper-server's /inference maps to /v1/audio/transcriptions in Radium's facade.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://github.com/ggml-org/whisper.cpp",
    },
    RuntimeDescriptor {
        id: "faster-whisper",
        name: "faster-whisper",
        group: Group::ImageVideoSpeech,
        tier: Tier::P0,
        mode: Mode::ManagedInstall,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: ASR,
        formats: &[F::Ct2],
        apis: PY,
        default_port: None,
        platforms: ALL,
        multi_gpu: MultiGpu::PerProcess,
        telemetry: &[WORKER],
        granularity: Granularity::PerRequest,
        license: MIT,
        maintenance: Maintenance::Active,
        note: "Runs on CTranslate2; pick the GPU with device_index.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://github.com/SYSTRAN/faster-whisper",
    },
    RuntimeDescriptor {
        id: "sherpa-onnx",
        name: "sherpa-onnx",
        group: Group::ImageVideoSpeech,
        tier: Tier::P2,
        mode: Mode::Bundled,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: &[C::SpeechToText, C::TextToSpeech],
        formats: &[F::Onnx],
        apis: &[A::CLibrary, A::Cli],
        default_port: None,
        platforms: ALL,
        multi_gpu: MultiGpu::PerProcess,
        telemetry: &[WORKER],
        granularity: Granularity::PerRequest,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "ASR, TTS and VAD with Windows prebuilts; model configuration differs by family.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://github.com/k2-fsa/sherpa-onnx",
    },
    RuntimeDescriptor {
        id: "piper",
        name: "Piper",
        group: Group::ImageVideoSpeech,
        tier: Tier::P0,
        mode: Mode::ManagedInstall,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: &[C::TextToSpeech],
        formats: &[F::Onnx],
        apis: &[A::PythonLibrary, A::Cli],
        default_port: None,
        platforms: ALL,
        multi_gpu: MultiGpu::NotApplicable,
        telemetry: &[WORKER],
        granularity: Granularity::PerRequest,
        license: GPL3,
        maintenance: Maintenance::Active,
        note: "Moved to OHF-Voice/piper1-gpl under GPL-3.0: install with pip on the user's action, never bundle. Each voice has its own licence in its MODEL_CARD.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://github.com/OHF-Voice/piper1-gpl",
    },
    // ===== Browser, mobile & edge =============================================
    RuntimeDescriptor {
        id: "webllm",
        name: "WebLLM",
        group: Group::BrowserMobileEdge,
        tier: Tier::OutOfScope,
        mode: Mode::OutOfScope,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: TEXT,
        formats: &[F::Mlc],
        apis: &[A::JavaScript],
        default_port: None,
        platforms: EDGE,
        multi_gpu: MultiGpu::NotApplicable,
        telemetry: &[],
        granularity: Granularity::None,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Duplicates the native engines on this workstation; only useful for a no-install web demo.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://webllm.mlc.ai/",
    },
    RuntimeDescriptor {
        id: "onnx-runtime-web",
        name: "ONNX Runtime Web",
        group: Group::BrowserMobileEdge,
        tier: Tier::P3,
        mode: Mode::InProcess,
        layer: Layer::Engine,
        wraps: NONE_WRAPS,
        capabilities: &[C::Embeddings, C::Vision, C::SpeechToText],
        formats: &[F::Onnx],
        apis: &[A::JavaScript],
        default_port: None,
        platforms: ALL,
        multi_gpu: MultiGpu::NotApplicable,
        telemetry: &[WORKER],
        granularity: Granularity::PerRequest,
        license: MIT,
        maintenance: Maintenance::Active,
        note: "Optional, in the web view for small models such as voice activity detection.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://onnxruntime.ai/docs/tutorials/web/",
    },
    RuntimeDescriptor {
        id: "apple-core-ml",
        name: "Apple Core ML",
        group: Group::BrowserMobileEdge,
        tier: Tier::OutOfScope,
        mode: Mode::OutOfScope,
        layer: Layer::Library,
        wraps: NONE_WRAPS,
        capabilities: &[],
        formats: &[F::CoreMl],
        apis: &[A::CLibrary],
        default_port: None,
        platforms: APPLE,
        multi_gpu: MultiGpu::NotApplicable,
        telemetry: &[],
        granularity: Granularity::None,
        license: CLOSED,
        maintenance: Maintenance::Active,
        note: "Apple hardware only.",
        verified: true,
        verified_on: CHECKED,
        source_url: "https://developer.apple.com/documentation/coreml",
    },
    RuntimeDescriptor {
        id: "google-litert",
        name: "Google LiteRT",
        group: Group::BrowserMobileEdge,
        tier: Tier::OutOfScope,
        mode: Mode::OutOfScope,
        layer: Layer::Library,
        wraps: NONE_WRAPS,
        capabilities: &[],
        formats: &[F::Tflite],
        apis: &[A::CLibrary],
        default_port: None,
        platforms: EDGE,
        multi_gpu: MultiGpu::NotApplicable,
        telemetry: &[],
        granularity: Granularity::None,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Phone and edge target; no advantage over ONNX Runtime or llama.cpp on 3090s.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://ai.google.dev/edge/litert",
    },
    RuntimeDescriptor {
        id: "executorch",
        name: "ExecuTorch",
        group: Group::BrowserMobileEdge,
        tier: Tier::OutOfScope,
        mode: Mode::OutOfScope,
        layer: Layer::Library,
        wraps: NONE_WRAPS,
        capabilities: &[],
        formats: &[F::Pte],
        apis: &[A::CLibrary],
        default_port: None,
        platforms: EDGE,
        multi_gpu: MultiGpu::NotApplicable,
        telemetry: &[],
        granularity: Granularity::None,
        license: BSD3,
        maintenance: Maintenance::Active,
        note: "Mobile and edge deployment of exported PyTorch programs.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://docs.pytorch.org/executorch/stable/runtime.html",
    },
    RuntimeDescriptor {
        id: "ncnn",
        name: "ncnn",
        group: Group::BrowserMobileEdge,
        tier: Tier::OutOfScope,
        mode: Mode::OutOfScope,
        layer: Layer::Library,
        wraps: NONE_WRAPS,
        capabilities: &[],
        formats: &[F::Ncnn],
        apis: &[A::CLibrary],
        default_port: None,
        platforms: EDGE,
        multi_gpu: MultiGpu::NotApplicable,
        telemetry: &[],
        granularity: Granularity::None,
        license: BSD3,
        maintenance: Maintenance::Active,
        note: "Mobile-first CPU/Vulkan runtime with no LLM server.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://github.com/Tencent/ncnn",
    },
    RuntimeDescriptor {
        id: "mnn",
        name: "MNN / MNN-LLM",
        group: Group::BrowserMobileEdge,
        tier: Tier::OutOfScope,
        mode: Mode::OutOfScope,
        layer: Layer::Library,
        wraps: NONE_WRAPS,
        capabilities: &[],
        formats: &[F::Mnn],
        apis: &[A::CLibrary],
        default_port: None,
        platforms: EDGE,
        multi_gpu: MultiGpu::NotApplicable,
        telemetry: &[],
        granularity: Granularity::None,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Mobile and edge target.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://github.com/alibaba/MNN",
    },
    RuntimeDescriptor {
        id: "paddle-fastdeploy",
        name: "Paddle FastDeploy",
        group: Group::BrowserMobileEdge,
        tier: Tier::OutOfScope,
        mode: Mode::OutOfScope,
        layer: Layer::Library,
        wraps: NONE_WRAPS,
        capabilities: &[],
        formats: &[F::Paddle, F::Onnx, F::TensorrtEngine],
        apis: &[A::PythonLibrary, A::CLibrary],
        default_port: None,
        platforms: LINUX_WSL,
        multi_gpu: MultiGpu::NotApplicable,
        telemetry: &[],
        granularity: Granularity::None,
        license: APACHE,
        maintenance: Maintenance::Active,
        note: "Paddle ecosystem, Linux-first serving.",
        verified: false,
        verified_on: CHECKED,
        source_url: "https://github.com/PaddlePaddle/FastDeploy",
    },
];

/// The runtime with this id, if the catalog has it.
pub fn find(id: &str) -> Option<&'static RuntimeDescriptor> {
    RUNTIMES.iter().find(|runtime| runtime.id == id)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn the_catalog_has_all_63_runtimes_once_each() {
        assert_eq!(RUNTIMES.len(), 63);
        let ids: HashSet<_> = RUNTIMES.iter().map(|runtime| runtime.id).collect();
        assert_eq!(ids.len(), RUNTIMES.len(), "duplicate id");
    }

    #[test]
    fn ids_are_stable_slugs() {
        for runtime in RUNTIMES {
            assert!(
                !runtime.id.is_empty()
                    && runtime
                        .id
                        .chars()
                        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
                    && !runtime.id.starts_with('-')
                    && !runtime.id.ends_with('-'),
                "bad id {:?}",
                runtime.id
            );
        }
    }

    #[test]
    fn every_group_matches_the_catalogs_section_sizes() {
        let count = |group| RUNTIMES.iter().filter(|r| r.group == group).count();
        assert_eq!(count(Group::LocalDesktop), 15);
        assert_eq!(count(Group::ThroughputServer), 15);
        assert_eq!(count(Group::ModelLibrary), 15);
        assert_eq!(count(Group::ImageVideoSpeech), 10);
        assert_eq!(count(Group::BrowserMobileEdge), 8);
    }

    #[test]
    fn out_of_scope_tier_and_mode_agree() {
        for runtime in RUNTIMES {
            assert_eq!(
                runtime.tier == Tier::OutOfScope,
                runtime.mode == Mode::OutOfScope,
                "{}",
                runtime.id
            );
        }
    }

    #[test]
    fn deferred_and_out_of_scope_entries_say_why() {
        for runtime in RUNTIMES {
            if matches!(runtime.tier, Tier::Deferred | Tier::OutOfScope) {
                assert!(runtime.note.len() > 10, "{} needs a reason", runtime.id);
            }
        }
    }

    /// Radium is Apache-2.0: copyleft code is downloaded on the user's action
    /// and run as its own process, never shipped inside the installer.
    #[test]
    fn copyleft_runtimes_are_never_bundled_or_linked() {
        for runtime in RUNTIMES {
            if runtime.license.class == LicenseClass::Copyleft {
                assert!(
                    !matches!(runtime.mode, Mode::Bundled | Mode::InProcess),
                    "{} is {} and must not be bundled",
                    runtime.id,
                    runtime.license.spdx
                );
            }
        }
    }

    #[test]
    fn closed_source_runtimes_are_attached_or_hosted_never_bundled() {
        for runtime in RUNTIMES {
            if runtime.license.class == LicenseClass::Proprietary {
                assert!(
                    !matches!(runtime.mode, Mode::Bundled | Mode::InProcess),
                    "{}",
                    runtime.id
                );
            }
        }
    }

    #[test]
    fn wrappers_name_the_engines_they_wrap_and_engines_wrap_nothing() {
        for runtime in RUNTIMES {
            match runtime.layer {
                Layer::Wrapper => {
                    assert!(!runtime.wraps.is_empty(), "{} wraps nothing", runtime.id);
                    for inner in runtime.wraps {
                        assert!(find(inner).is_some(), "{} wraps unknown {inner}", runtime.id);
                        assert_ne!(*inner, runtime.id);
                    }
                }
                Layer::Engine | Layer::Library => {
                    assert!(runtime.wraps.is_empty(), "{}", runtime.id)
                }
            }
        }
    }

    #[test]
    fn linux_only_runtimes_are_wsl_hosted_attached_or_out_of_scope_on_windows() {
        for runtime in RUNTIMES {
            if runtime.platforms.windows == Support::Wsl {
                assert!(
                    matches!(
                        runtime.mode,
                        Mode::WslHosted | Mode::Attach | Mode::OutOfScope
                    ),
                    "{} has no native Windows build but mode {:?}",
                    runtime.id,
                    runtime.mode
                );
            }
        }
    }

    #[test]
    fn archived_or_maintenance_mode_runtimes_are_not_scheduled_for_building() {
        for runtime in RUNTIMES {
            if matches!(
                runtime.maintenance,
                Maintenance::Archived | Maintenance::MaintenanceMode
            ) {
                assert!(
                    matches!(runtime.tier, Tier::Deferred | Tier::OutOfScope),
                    "{}",
                    runtime.id
                );
            }
        }
    }

    #[test]
    fn a_prometheus_source_names_its_path_and_prefix() {
        for runtime in RUNTIMES {
            for source in runtime.telemetry {
                if let T::Prometheus { path, prefix, .. } = source {
                    assert!(path.starts_with('/'), "{}", runtime.id);
                    assert!(!prefix.is_empty(), "{}", runtime.id);
                }
            }
        }
    }

    #[test]
    fn source_urls_are_https() {
        for runtime in RUNTIMES {
            assert!(runtime.source_url.starts_with("https://"), "{}", runtime.id);
        }
    }

    #[test]
    fn the_first_phase_matches_the_plan() {
        let mut p0: Vec<_> = RUNTIMES
            .iter()
            .filter(|r| r.tier == Tier::P0)
            .map(|r| r.id)
            .collect();
        p0.sort_unstable();
        assert_eq!(
            p0,
            [
                "comfyui",
                "faster-whisper",
                "koboldcpp",
                "llama-cpp",
                "lm-studio",
                "ollama",
                "onnx-runtime",
                "piper",
                "radium",
                "stable-diffusion-cpp",
                "whisper-cpp",
            ]
        );
    }
}
